---

# Variables setup
- name: Include os-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Run os-specific specific setup
  include: "setup-{{ ansible_os_family }}.yml"

# Install the Docker repository
- include: "repo-{{ ansible_os_family }}.yml"
  when: not skip_repo

# Install the Docker Engine
- include: setup-docker-engine.yml
  when: not skip_engine

# Install docker-py
- include: setup-docker-py.yml
  when: not skip_docker_py

# Adds the Docker admin users to the Docker group
- include: setup-docker-group.yml
  when: not skip_group

# Setup the Docker Swarm Cluster
- block:
    - include: setup-swarm-cluster.yml
    - include: setup-swarm-labels.yml
  when: not skip_swarm
