---
- name: Add the Docker administrators to the Docker group
  user:
    name: "{{ item }}"
    groups: "{{ docker_group_name }}"
    append: true
  register: addtogroup
  become: true
  with_items: "{{ docker_group_users }}"

- name: Gather users which were added during this run
  set_fact:
    __docker_users_added: "{{ addtogroup.results | selectattr('changed') | map(attribute='item') | list }}"

- block:
    # See https://stackoverflow.com/a/44753457
    - name: Reset ansible connection after group changes (Ansible >= 2.3.0).
      include_tasks: reset-connection.yml
      # we need to force dynamic inclusion here to avoid 'reset_connection' to be
      # always executed even if the when condition evaluates to false on Ansible 2.4.x
      # or to generate syntax errors on Ansible < 2.3
      when: ansible_version is defined
        and (ansible_version.full is version('2.3.0.0', '>='))

  when: ansible_connection in ['ssh', 'smart']
    and ansible_user is defined
    and ansible_user in docker_group_users
    and ansible_user in __docker_users_added
